[server]
ip = "145.94.124.20"
port = 8080
timeout = 1

[data]
save = true
path = "data/"
format = "%d-%m-%Y_%H-%M-%S"

[plot]
time_window = 60 # s
dt = 0.1 # s
size = [14, 8] # inches

[plot.upper_left]
signals = ["fx_rel", "fy_rel", "fz_rel"]
colors = ["black", "blue", "green"]
limits = [-3, 0]
title = "force"
ylabel = "force (N)"

[plot.lower_left]
signals = ["s0v", "s1v", "s2v", "s3v"]
colors = ["black", "blue", "green", "yellow"]
limits = [0, 4600]
title = "raw sensor value"
ylabel = "value (bits)"

[plot.right]
signals = ["s0v_rel", "s1v_rel", "s2v_rel", "s3v_rel"]
colors = ["red", "green", "blue", "yellow"]
limits = [0, 20]
title = "sensor values"
ylabel = "value (%)"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"
