[server]
ip = "10.118.70.12"
port = 8080
timeout = 1

[data]
save = true
path = "data/"
format = "%d-%m-%Y_%H-%M-%S"

[plot]
time_window = 120 # s
dt = 0.01 # s
size = [14, 8] # inches

[plot.upper_left]
signals = ["voltage", "voltage_filt"]
colors = ["black", "blue"]
limits = [0, 5]
title = "Voltage"
ylabel = "Voltage (V)"

[plot.lower_left]
signals = ["reference", "strain"]
colors = ["black", "red"]
limits = [0, 50]
title = "Reference and Strain"
ylabel = "Strain (%)"

[plot.right]
signals = ["voltage_rel", "voltage_filt_rel"]
colors = ["black", "yellow"]
limits = [0, 100]
title = "AR/R (%)"
ylabel = "AR/R (%)"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"
