[server]
ip = "auto"
port = 8080
timeout = 2

[data]
save = false
path = "data/"
date_format = "%d-%m-%Y_%H-%M-%S"

[figure]
save = false
path = "figures/"
format = "png"
date_format = "%d-%m-%Y_%H-%M-%S"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"

[plot]
layout = "2x2"
time_window = 30 # s
dt = 0.01 # s
size = [14, 8] # inches
padding = 0.05

[plot."(0,0)"]
x = "time"
y = ["fx", "fy", "fz"]
colors = ["red", "green", "blue"]
xlabel = "time (s)"
ylabel = "force (N)"
limits = [-2, 2]
title = "force"
n_ticks = 10

[plot."(1,0)"]
x = "time"
y = ["mx", "my", "mz"]
colors = ["red", "green", "blue"]
xlabel = "time (s)"
ylabel = "torque (Nm)"
limits = [-1, 1]
title = "torque"
n_ticks = 10

[plot."(:,1)"]
x = "time"
y = ["s0", "s1", "s2", "s3"]
xlabel = "time (s)"
ylabel = "value (%)"
colors = ["red", "green", "blue", "yellow"]
limits = [-5, 30]
title = "values"
n_ticks = 20

