[server]
ip = "145.94.124.38"
port = 8080
timeout = 1

[data]
save = true
path = "/Users/vistor/Documents/tmp_/tactile-data/raspi-data/"
date_format = "%d-%m-%Y_%H-%M-%S"

[figure]
save = false
path = "figures/"
format = "png"
date_format = "%d-%m-%Y_%H-%M-%S"

[plot]
time_window = 60 # s
dt = 0.01 # s
size = [14, 8] # inches

[plot.upper_left]
x = "time"
signals = ["fx", "fy", "fz"]
colors = ["black", "blue", "green"]
limits = [-3, 0]
title = "force"
ylabel = "force (N)"

[plot.lower_left]
x = "time"
signals = ["mx", "my", "mz"]
colors = ["black", "blue", "green"]
limits = [-2, 2]
title = "torque"
ylabel = "torque (Nm)"

[plot.right]
x = "time"
signals = ["s0", "s1", "s2", "s3"]
colors = ["red", "green", "blue", "yellow"]
limits = [0, 10]
title = "values"
ylabel = "value (%)"

[colors]
red = "#cf7171"
green = "#dbe8c1"
blue = "#aecdd2"
yellow = "#fadf7f"
purple = "#c696bc"
black = "#4d5359"
